server.port=8088
spring.application.name=restaurant-service

#configure eureka client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


# Actuator configurations
management.endpoints.web.exposure.include=*
management.info.env.enabled=true