spring.datasource.url=jdbc:postgresql://localhost:5432/restaurantdb
spring.datasource.username=admin
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
# silence the open-in-view warning (recommended for services)
spring.jpa.open-in-view=false   
#Hibername properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

info.app.name=restaurant-service
info.app.description=This is restaurant service on dev enviornament env
info.app.version=1.0 Dev
